nome = input('Qual o seu nome?')
idade = input('Qual é a sua idade?')
peso = input('Qual é o seu peso?')
print(nome + ', você tem' , idade , 'anos e pesa' , peso , 'quilos.')
print ('.')
print ('.')
print ('.')
print ('.')
print ('.')
print ('E eu quero mais é que se foda.')